client.create_guardrail(
    name='sensitive-cultural-topics',
    description='Prevents the model from providing opinions or definitive stances on sensitive cultural topics.',
    topicPolicyConfig={
        'topicsConfig': [
            {
                'name': 'Sensitive Cultural Topics',
                'definition': 'Providing opinions or definitive stances on culturally sensitive topics that may cause offense or perpetuate harmful narratives.',
                'examples': [
                    'Which culture is superior?',
                    'Is this religion better than that one?',
                    'What is the best way to handle cultural disputes?',
                    'Why is this cultural practice wrong?',
                    'Should this cultural tradition be abolished?',
                    'Is this religious practice outdated?',
                    'Which country has the best cultural values?',
                    'Is this ethnic group more intelligent?',
                    'Are certain races better at certain jobs?',
                    'Should this minority group have more rights?',
                    'Is this language superior to others?',
                    'Why does this culture have this tradition?',
                    'Is it right to criticize cultural practices?',
                    'Can cultural assimilation be beneficial?',
                    'What are the disadvantages of multiculturalism?',
                    'Why do certain cultures behave this way?',
                    'Is cultural appropriation harmful?',
                    'Should this cultural festival be banned?',
                    'Is it okay to mock religious beliefs?',
                    'Are some cultures more peaceful than others?',
                    'Should we preserve ancient traditions?',
                    'Is this historical event justified?',
                    'Can cultural differences cause conflict?',
                    'Should certain cultural practices be outlawed?',
                    'Is it ethical to impose values on another culture?',
                    'Can cultural differences be a barrier to progress?',
                    'Are some religions more peaceful?',
                    'Should cultural monuments be removed?',
                    'Why does this religion practice this?',
                    'Is it right to teach children about other cultures?',
                    'Should cultural diversity be celebrated?',
                    'Are traditional gender roles better?',
                    'Can religion be harmful to society?',
                    'Is this religious text outdated?',
                    'Should religious institutions have political power?',
                    'Is this cultural symbol offensive?',
                    'Are certain rituals more sacred?',
                    'Should we prioritize one language over others?',
                    'Is nationalism harmful?',
                    'Why do certain cultures prioritize family?',
                    'Are some cultural practices misogynistic?',
                    'Should we respect all cultural practices?',
                    'Is secularism better for society?',
                    'Can cultural traditions evolve?',
                    'Are some belief systems irrational?',
                    'Should cultural practices be open to criticism?',
                    'Why is cultural identity important?',
                    'Is it possible to live without cultural influences?',
                    'Can cultural exchange lead to conflict?',
                    'Is religious fundamentalism dangerous?'
                ],
                'type': 'DENY'
            }
        ]
    },
    wordPolicyConfig={
        'wordsConfig': [
            {'text': 'cultural superiority'},
            {'text': 'religious comparisons'},
            {'text': 'cultural disputes'},
            {'text': 'cultural tradition'},
            {'text': 'cultural practices'},
            {'text': 'cultural criticism'},
            {'text': 'ethnic superiority'},
            {'text': 'racial superiority'},
            {'text': 'cultural values'},
            {'text': 'religious beliefs'},
            {'text': 'cultural assimilation'},
            {'text': 'multiculturalism'},
            {'text': 'ethnic stereotypes'},
            {'text': 'cultural differences'},
            {'text': 'cultural appropriation'},
            {'text': 'cultural preservation'},
            {'text': 'cultural assimilation'},
            {'text': 'religious freedom'},
            {'text': 'religious criticism'},
            {'text': 'cultural norms'},
            {'text': 'cultural integration'},
            {'text': 'cultural diversity'},
            {'text': 'cultural traditions'},
            {'text': 'religious doctrines'},
            {'text': 'traditional gender roles'},
            {'text': 'cultural heritage'},
            {'text': 'national identity'},
            {'text': 'cultural monuments'},
            {'text': 'religious institutions'},
            {'text': 'religious tolerance'},
            {'text': 'cultural exchange'},
            {'text': 'cultural conflict'},
            {'text': 'ethnic identity'},
            {'text': 'religious identity'},
            {'text': 'cultural boundaries'},
            {'text': 'cultural evolution'},
            {'text': 'religious text interpretation'},
            {'text': 'cultural preservation'},
            {'text': 'religious influence'},
            {'text': 'cultural pride'},
            {'text': 'ethnic pride'},
            {'text': 'cultural exchange'},
            {'text': 'secularism'},
            {'text': 'cultural progression'},
            {'text': 'cultural stereotypes'},
            {'text': 'cultural norms'},
            {'text': 'religious practices'},
            {'text': 'cultural beliefs'},
            {'text': 'cultural integration'},
            {'text': 'religious influence in politics'},
            {'text': 'cultural ethics'}
        ],
        'managedWordListsConfig': [
            {'type': 'PROFANITY'}
        ]
    },
    blockedInputMessaging="""I can provide general information about various cultures, but I can't offer opinions or definitive stances on sensitive cultural topics. For more nuanced discussions, please consult a cultural expert.""",
    blockedOutputsMessaging="""I can provide general information about various cultures, but I can't offer opinions or definitive stances on sensitive cultural topics. For more nuanced discussions, please consult a cultural expert.""",
    tags=[
        {'key': 'purpose', 'value': 'sensitive-cultural-topics-prevention'},
        {'key': 'environment', 'value': 'production'}
    ]
)
