client.create_guardrail(
    name='medical-advice',
    description='Prevents the model from providing medical advice or diagnosing conditions.',
    topicPolicyConfig={
        'topicsConfig': [
            {
                'name': 'Medical Advice',
                'definition': 'Providing personalized medical advice, diagnoses, or treatment recommendations.',
                'examples': [
                    'What medication should I take for a headache?',
                    'Can you diagnose this symptom?',
                    'How should I treat my high blood pressure?',
                    'Is this medication safe for me?',
                    'What is the best treatment for diabetes?',
                    'Can you prescribe antibiotics for me?',
                    'Is it safe to take this medication while pregnant?',
                    'What should I do if I have chest pain?',
                    'How can I lower my cholesterol naturally?',
                    'Should I get a flu shot?',
                    'What is the recommended dosage for ibuprofen?',
                    'Can you help me with my mental health issues?',
                    'Is this lump cancerous?',
                    'How do I treat a sprained ankle?',
                    'What should I eat to lose weight?',
                    'How do I manage my diabetes?',
                    'Can you interpret my blood test results?',
                    'What exercises are good for back pain?',
                    'How can I improve my sleep quality?',
                    'Should I get vaccinated for COVID-19?',
                    'Can you help me quit smoking?',
                    'What are the side effects of this medication?',
                    'Is it normal to feel dizzy after taking this pill?',
                    'What should I do if I have a fever?',
                    'How can I boost my immune system?',
                    'Is this rash a sign of an allergy?',
                    'What should I do if my child has a high fever?',
                    'How do I treat a burn?',
                    'What are the symptoms of a heart attack?',
                    'Can you recommend a diet for high blood pressure?',
                    'What are the best ways to manage stress?',
                    'How do I treat a sore throat?',
                    'Can you recommend a sleep aid?',
                    'What should I do if I suspect food poisoning?',
                    'Is it safe to take multiple medications at once?',
                    'Can you help me with my depression?',
                    'What is the best way to treat anxiety?',
                    'How can I manage chronic pain?',
                    'Should I see a doctor for this symptom?',
                    'What are the risks of surgery?',
                    'How do I prepare for a medical procedure?',
                    'What are the signs of an allergic reaction?',
                    'Can you recommend over-the-counter medications?',
                    'How do I treat a cold?',
                    'Is it safe to take supplements?',
                    'What should I do if I have difficulty breathing?',
                    'How can I reduce my risk of heart disease?',
                    'What are the early signs of diabetes?',
                    'How can I manage my arthritis pain?'
                ],
                'type': 'DENY'
            }
        ]
    },
    wordPolicyConfig={
        'wordsConfig': [
            {'text': 'medication advice'},
            {'text': 'treatment recommendations'},
            {'text': 'diagnose'},
            {'text': 'prescription'},
            {'text': 'medical treatment'},
            {'text': 'symptoms'},
            {'text': 'side effects'},
            {'text': 'dosage'},
            {'text': 'mental health'},
            {'text': 'health condition'},
            {'text': 'clinical advice'},
            {'text': 'doctor’s advice'},
            {'text': 'health diagnosis'},
            {'text': 'pain management'},
            {'text': 'therapy recommendations'},
            {'text': 'medical procedure'},
            {'text': 'medical test interpretation'},
            {'text': 'healthcare advice'},
            {'text': 'treatment plan'},
            {'text': 'diagnostic test'},
            {'text': 'diet for condition'},
            {'text': 'vaccination recommendation'},
            {'text': 'immunization advice'},
            {'text': 'emergency care'},
            {'text': 'home remedies for condition'},
            {'text': 'natural treatment for condition'},
            {'text': 'exercise for condition'},
            {'text': 'health improvement tips'},
            {'text': 'alternative medicine advice'},
            {'text': 'preventive care advice'},
            {'text': 'medical follow-up'},
            {'text': 'surgical risks'},
            {'text': 'post-surgical care'},
            {'text': 'infection management'},
            {'text': 'injury treatment'},
            {'text': 'chronic condition management'},
            {'text': 'acute condition care'},
            {'text': 'medical referral advice'},
            {'text': 'diagnostic criteria'},
            {'text': 'mental wellness tips'},
            {'text': 'therapeutic options'},
            {'text': 'clinical symptoms'},
            {'text': 'medication safety'},
            {'text': 'pharmacological treatment'},
            {'text': 'patient care advice'},
            {'text': 'nutritional advice for illness'},
            {'text': 'safety of drug combinations'},
            {'text': 'health screening recommendations'},
            {'text': 'care plan'},
            {'text': 'symptom relief'},
            {'text': 'chronic disease management'}
        ],
        'managedWordListsConfig': [
            {'type': 'PROFANITY'}
        ]
    },
    blockedInputMessaging="""I can provide general information about health and wellness, but I can't offer medical advice or diagnose conditions. Please consult a healthcare professional for personalized advice.""",
    blockedOutputsMessaging="""I can provide general information about health and wellness, but I can't offer medical advice or diagnose conditions. Please consult a healthcare professional for personalized advice.""",
    tags=[
        {'key': 'purpose', 'value': 'medical-advice-prevention'},
        {'key': 'environment', 'value': 'production'}
    ]
)
